services:
  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - fraud-test-network
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  # Android Node
  android-node:
    image: selenium/node-android:latest
    container_name: android-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - DEVICE_NAME=Android_Emulator
      - PLATFORM_NAME=Android
      - PLATFORM_VERSION=11.0
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - fraud-test-network
    privileged: true

  # Mock API Server
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile.mock-server
    container_name: fraud-mock-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MOCK_SERVER_PORT=3000
      - MOCK_LOG_LEVEL=info
    networks:
      - fraud-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Appium Server
  appium-server:
    build:
      context: .
      dockerfile: Dockerfile.appium
    container_name: fraud-appium-server
    ports:
      - "4723:4723"
    environment:
      - APPIUM_HOST=0.0.0.0
      - APPIUM_PORT=4723
    volumes:
      - ./app:/app/app:ro
      - ./logs:/app/logs
    networks:
      - fraud-test-network
    depends_on:
      - selenium-hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4723/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test Runner
  fraud-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-test-runner
    environment:
      - API_BASE_URL=http://mock-api:3000
      - APPIUM_HOST=appium-server
      - APPIUM_PORT=4723
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
      - PLATFORM=android
      - ENVIRONMENT=docker
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./screenshots:/app/screenshots
    networks:
      - fraud-test-network
    depends_on:
      - mock-api
      - appium-server
      - android-node
    command: ["npm", "test"]

  # Allure Report Server
  allure-reports:
    image: frankescobar/allure-docker-service
    container_name: fraud-allure-reports
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports
    networks:
      - fraud-test-network

networks:
  fraud-test-network:
    driver: bridge
    name: fraud-test-network

volumes:
  allure-results:
  allure-reports:
  test-logs: